In [1]:
import pandas as pd
from pycaret.classification import *
import numpy as np
from openpyxl import Workbook, load_workbook
from xlsxwriter import Workbook
from time import sleep
from datetime import date, datetime, timedelta

def drop_reset_index(df):
    df = df.dropna()
    df = df.reset_index(drop=True)
    df.index += 1
    return df

In [2]:
caminho1 = "C:/Users/thiag/OneDrive/curso python/modelo_leandro_2/"
jogos_dia_completo = pd.read_csv(caminho1 + 'jogos_estatistica.csv')

dia = date.today()
# + timedelta(1)

jogos_do_dia = pd.read_excel("C:/Users/thiag/OneDrive/curso python/modelo_leandro_2/2023-07-04_Jogos_do_Dia_arkad_transform(last).xlsx")

In [14]:
flt = jogos_do_dia.League == "USA - MLS"
jogos_do_dia = jogos_do_dia[flt]
jogos_do_dia = drop_reset_index(jogos_do_dia)
saved_final_lr = load_model('LAYAWAY_ARKAD_USA - MLS')
new_predictions = predict_model(saved_final_lr, data=jogos_do_dia)
new_predictions

Transformation Pipeline and Model Successfully Loaded

,p_H,p_D,p_A,CV_VG_H,CV_VG_A,coeficiente_pontos,cv_pontos,CV_HDA,prediction_label
1,0.347222,0.285714,0.420168,0.609200,0.455102,0.5,2.583935,0.156888,1
2,0.625000,0.250000,0.181818,0.679785,1.111551,0.2,2.487434,0.434118,1
3,0.434783,0.294118,0.333333,0.730005,0.914766,0.3,2.533523,0.156761,1
4,0.465116,0.294118,0.294118,1.054443,0.899339,0.0,1.743560,0.197516,1
5,0.277778,0.266667,0.512821,0.667903,0.963706,0.4,2.120779,0.263057,1

In [15]:
base_H = new_predictions[['p_H', 'CV_VG_H', 'cv_pontos']]
    
base_A = dnew_predictions[['p_A', 'CV_VG_A', 'cv_pontos']]

In [18]:
lista=[]

for a,b,c,d,e,f,g,h,i,j,k,l in zip(jogos_do_dia.League,jogos_do_dia.Date,jogos_do_dia.Time,jogos_do_dia.Home,jogos_do_dia.Away,
                                   jogos_do_dia.FT_Odd_H,jogos_do_dia.FT_Odd_D,jogos_do_dia.FT_Odd_A,jogos_do_dia.FT_Odd_Over25,jogos_do_dia.FT_Odd_Under25,
                                   jogos_do_dia.FT_Odd_BTTS_Yes,jogos_do_dia.FT_Odd_BTTS_No):
        League = a
        Date = b
        Time = c 
        home = d
        away = e
        FT_Odd_H = f
        FT_Odd_D = g
        FT_Odd_A = h
        FT_Odd_Over25 = i
        FT_Odd_Under25 = j
        FT_Odd_BTTS_Yes = k
        FT_Odd_BTTS_No = l
  
        df1 = base_H[base_H.cv_pontos == home].tail(1)

        df2 = base_A[base_A.cv_pontos == away].tail(1)

        jogo = {}

        jogo["League"] = League 
        jogo["Date"] = Date
        jogo["Time"] = Time
        jogo["Home"] = home
        jogo["Away"] = away
        jogo["FT_Odd_H"] = FT_Odd_H
        jogo["FT_Odd_D"] = FT_Odd_D
        jogo["FT_Odd_A"] = FT_Odd_A
        jogo["FT_Odd_Over25"] = FT_Odd_Over25
        jogo["FT_Odd_Under25"] = FT_Odd_Under25
        jogo["FT_Odd_BTTS_Yes"] = FT_Odd_BTTS_Yes
        jogo["FT_Odd_BTTS_No"] = FT_Odd_BTTS_No

        
        try:
        
            jogo['p_H'] = df1[df1.cv_pontos == home]['p_H'].iloc[0]
            jogo['CV_VG_H'] = df1[df1.cv_pontos == home]['CV_VG_H'].iloc[0]
        
            jogo['CV_VG_A'] = df2[df2.Away == away]['CV_VG_A'].iloc[0]
            jogo['p_A'] = df2[df2.Away == away]['p_A'].iloc[0]
    
            
                
            
        except:
            pass
        
        lista.append(jogo)


df = pd.DataFrame(lista)
df.reset_index(inplace=True, drop=True)
df.index = df.index.set_names(['Nº'])
df = df.rename(index=lambda x: x + 1)

In [19]:
df

,League,Date,Time,Home,Away,FT_Odd_H,FT_Odd_D,FT_Odd_A,FT_Odd_Over25,FT_Odd_Under25,FT_Odd_BTTS_Yes,FT_Odd_BTTS_No
Nº,,,,,,,,,,,,
1,USA - MLS,04/07/2023,20:30,Inter Miami,Columbus Crew,2.88,3.50,2.38,1.67,2.15,1.53,2.38
2,USA - MLS,04/07/2023,20:30,Orlando City,Toronto FC,1.60,4.00,5.50,1.70,2.10,1.80,1.95
3,USA - MLS,04/07/2023,21:30,FC Dallas,DC United,2.30,3.40,3.00,2.03,1.83,1.80,1.95
4,USA - MLS,04/07/2023,22:30,Colorado Rapids,Portland Timbers,2.15,3.40,3.40,1.95,1.90,1.75,2.00
5,USA - MLS,04/07/2023,23:30,Los Angeles Galaxy,Los Angeles FC,3.60,3.75,1.95,1.62,2.25,1.57,2.25

In [16]:
df4 = pd.merge(df, new_predictions, how='left', on=["CV_VG_H"])